fetch:
    - class: APP
      name: IM
      desc: 社交聊天
      app_list:
          - name: telegram
            key: telegram
            app_id: '1030063'
            desc: Telegram
          - name: sugram
            key: sugram
            app_id: '1030215'
            desc: Sugram
          - name: skype
            key: skype
            app_id: '1030027'
            desc: Skype
          - name: crait
            key: crait
            app_id: 'no_68a9a29e'
            desc: Crait
          - name: imo
            key: imo
            app_id: '1030210'
            desc: imo
          - name: letstalk
            key: letstalk
            app_id: 'no_7bfd41fc'
            desc: letstalk
          - name: zalo
            key: zalo
            app_id: '1030122'
            desc: Zalo
          - name: linkedin
            key: linkedin
            app_id: '1030211'
            desc: LinkedIn
          - name: messenger
            key: messenger
            app_id: 'no_9121f80c'
            desc: Messenger
          - name: tamtam
            key: tamtam
            app_id: 'no_9a9c1476'
            desc: tamtam
          - name: whatsapp
            key: whatsapp
            app_id: '1030038'
            desc: WhatsApp
          - name: tantan
            key: tantan
            app_id: '1030206'
            desc: 探探
          - name: gagahi
            key: gagahi
            app_id: '1030155'
            desc: GaGaHi
    - class: APP
      name: SHOPPING
      desc: 电子商务
      app_list:
          - name: waimai
            key: waimai
            app_id: '1229996'
            desc: 美团外卖
    #       - name: taobao
    #         packages:
    #             - com.taobao.taobao
    #         app_id: '1220007'
    #         desc: 淘宝
    #       - name: taobao
    #         packages:
    #             - com.taobao.taobao
    #         app_id: '1220007'
    #         desc: 淘宝
    #       - name: tmall
    #         packages:
    #             - com.tmall.wireless
    #         app_id: '1220002'
    #         desc: 天猫
    #       - name: suning
    #         packages:
    #             - com.suning.mobile.ebuy
    #         app_id: '1220006'
    #         desc: 苏宁易购
    #       - name: wangyiyanxuan
    #         packages:
    #             - unknow
    #         app_id: '1220081'
    #         desc: 网易严选
    #       - name: meituan
    #         packages:
    #             - com.sankuai.meituan
    #         app_id: '1220040'
    #         desc: 美团
    #       - name: jumei
    #         packages:
    #             - unknow
    #         app_id: '1220013'
    #         desc: 聚美优品
    #       - name: weipinhui
    #         packages:
    #             - unknow
    #         app_id: '1220012'
    #         desc: 唯品会
    #       - name: mogujie
    #         packages:
    #             - unknow
    #         app_id: '1220042'
    #         desc: 蘑菇街
    #       - name: kaola
    #         packages:
    #             - unknow
    #         app_id: '1220061'
    #         desc: 考拉海购
    #       - name: xiaomishopping
    #         packages:
    #             - unknow
    #         app_id: '1220073'
    #         desc: 小米商城
    #       - name: yigou
    #         packages:
    #             - unknow
    #         app_id: '1220079'
    #         desc: 易购网
    - class: APP
      name: EMAIL
      desc: 电子邮件
      app_list:
          - name: outlook
            key: outlook
            app_id: '1010032'
            desc: Outlook
          - name: gmail
            key: gmail
            app_id: '1010033'
            desc: Gmail
          - name: yahoo
            key: yahoo
            app_id: '1010034'
            desc: Yahoo邮箱
          - name: mail139
            key: mail139
            app_id: '1010012'
            desc: 139邮箱
          - name: 189mail
            key: 189mail
            app_id: '1010013'
            desc: 189邮箱
    - class: APP
      name: WEIBO
      desc: 社交自媒体
      app_list:
          - name: sinaweibo
            key: sinaweibo
            app_id: '1330001'
            desc: 新浪微博
          - name: twitter
            key: twitter
            app_id: '1330005'
            desc: Twitter
          - name: instagram
            key: instagram
            app_id: '1330014'
            desc: Instagram
          - name: huya
            key: huya
            app_id: '1550019'
            desc: 虎牙直播
          - name: momo
            key: momo
            app_id: '1030044'
            desc: 陌陌
    # - class: APP
    #   name: MAP
    #   desc: 地图应用
    #   app_list:
    #       - name: baidu-map
    #         packages:
    #             - com.baidu.BaiduMap
    #         app_id: '1440004'
    #         desc: 百度地图
    #       - name: amap
    #         packages:
    #             - com.autonavi.minimap
    #         app_id: '1440003'
    #         desc: 高德地图
    - class: APP
      name: TRAVEL
      desc: 旅业预定
      app_list:
          - name: didi
            key: didi
            app_id: '1520001'
            desc: 滴滴出行
          # - name: ctrip
          #   packages:
          #       - ctrip.android.view
          #   app_id: '1260004'
          #   desc: 携程旅行
          # - name: qunar
          #   packages:
          #       - com.Qunar
          #   app_id: '1260007'
          #   desc: 去哪儿
          # - name: elong
          #   packages:
          #       - com.dp.android.elong
          #   app_id: '1260006'
          #   desc: 艺龙旅行
          - name: caocao
            key: caocao
            app_id: '1520058'
            desc: 曹操出行
          # - name: tuniu
          #   packages:
          #       - unknow
          #   app_id: '1230009'
          #   desc: 途牛
          # - name: huazhu
          #   packages:
          #       - unknow
          #   app_id: '1230003'
          #   desc: 华住会
          # - name: qiongyou
          #   packages:
          #       - unknow
          #   app_id: '1230035'
          #   desc: 穷游网
    - class: APP
      name: NETDISK
      desc: 网络共享
      app_list:
          - name: onedrive
            key: onedrive
            app_id: 'no_b92dd0ca'
            desc: OneDrive
          # - name: baidupan
          #   packages:
          #       - com.baidu.netdisk
          #   app_id: '1280015'
          #   desc: 百度网盘
          - name: mi
            key: mi
            app_id: '1280032'
            desc: 小米云服务
          - name: wps
            key: wps
            app_id: '1280028'
            desc: WPS
    - class: APP
      name: EXPRESS
      desc: 快递包裹
      app_list:
          - name: shunfeng
            key: shunfeng
            app_id: '1240003'
            desc: 顺丰快递
          - name: yto
            key: yto
            app_id: '1240002'
            desc: 圆通快递
          - name: zto
            key: zto
            app_id: '1240007'
            desc: 中通快递
          - name: sto
            key: sto
            app_id: '1240005'
            desc: 申通快递
          - name: yunda
            key: yunda
            app_id: '1240004'
            desc: 韵达快递
          - name: ems
            key: ems
            app_id: '1240001'
            desc: 邮政EMS
          - name: dada
            key: dada
            app_id: '1520504'
            desc: 达达快递
          - name: deppon
            key: deppon
            app_id: '1240011'
            desc: 德邦快递
          - name: fcbox
            key: fcbox
            app_id: 'no_f3160ec4'
            desc: 丰巢
          - name: huolala
            key: huolala
            app_id: '1520501'
            desc: 货拉拉
    - class: APP
      name: OTHERS
      desc: 其他
      app_list:
          - name: '10086'
            key: '10086'
            app_id: 'no_55877b82'
            desc: 中国移动
          - name: '10010'
            key: '10010'
            app_id: '1220018'
            desc: 中国联通
          - name: '10000'
            key: '10000'
            app_id: 'no_592dc87c'
            desc: 中国电信