fetch:
    - class: APP
      name: IM
      desc: 即时通讯
      select: 0
      app_list:
          - name: wechat
            packages:
                - com.tencent.mm
                - com.excelliance.dualaid
                - com.huihu.multplugin01
                - com.huihu.multplugin02
                - com.huihu.multplugin03
                - com.huihu.multplugin04
                - com.huihu.multplugin05
                - com.tencent.mm_cm
                - com.lbe.parallel
            app_id: '1030036'
            desc: 微信
            select: 0
    - class: APP
      name: TRAVEL
      desc: 行程
      select: 0
      app_list:
          - name: didicar
            packages:
                - com.sdu.didi.psnger
            app_id: '1520001'
            desc: 滴滴打车
            select: 0
