fetch:
    - class: APP
      name: TRAVEL
      desc: 行程
      select: 0
      app_list:
          - name: didicar
            packages:
                - com.sdu.didi.psnger
            app_id: '1520001'
            desc: 滴滴打车
            select: 0
