fetch:
    - class: APP
      name: IM
      desc: 社交聊天
      app_list:
          - name: telegram
            key: telegram
            app_id: '1030063'
            desc: Telegram
          - name: sugram
            key: sugram
            app_id: '1030215'
            desc: Sugram
          - name: skype
            key: skype
            app_id: '1030027'
            desc: Skype
          - name: crait
            key: crait
            app_id: 'no_68a9a29e'
            desc: Crait
          - name: imo
            key: imo
            app_id: '1030210'
            desc: imo
          - name: letstalk
            key: letstalk
            app_id: 'no_7bfd41fc'
            desc: letstalk
          - name: zalo
            key: zalo
            app_id: '1030122'
            desc: Zalo
          - name: linkedin
            key: linkedin
            app_id: '1030211'
            desc: LinkedIn
          - name: messenger
            key: messenger
            app_id: 'no_9121f80c'
            desc: Messenger
          - name: tamtam
            key: tamtam
            app_id: 'no_9a9c1476'
            desc: tamtam
          - name: whatsapp
            key: whatsapp
            app_id: '1030038'
            desc: WhatsApp
          - name: tantan
            key: tantan
            app_id: '1030206'
            desc: 探探
          - name: gagahi
            key: gagahi
            app_id: '1030155'
            desc: GaGaHi
    - class: APP
      name: SHOPPING
      desc: 电子商务
      app_list:
          - name: alipay
            key: unknown
            app_id: '1290007'
            desc: 支付宝
          - name: waimai
            key: waimai
            app_id: '1229996'
            desc: 美团外卖
          - name: taobao
            key: unknown
            app_id: '1220007'
            desc: 淘宝
          - name: tmall
            key: unknown
            app_id: '1220002'
            desc: 天猫
          - name: suning
            key: unknown
            app_id: '1220006'
            desc: 苏宁易购
          - name: wangyiyanxuan
            key: unknow
            app_id: '1220081'
            desc: 网易严选
          - name: meituan
            key: unknown
            app_id: '1220040'
            desc: 美团
          - name: jumei
            key: unknown
            app_id: '1220013'
            desc: 聚美优品
          - name: kongfuzi
            key: unknown
            app_id: 'no_6c4724df'
            desc: 孔夫子旧书网
          - name: weipinhui
            key: unknown
            app_id: '1220012'
            desc: 唯品会
          - name: yiyaowang
            key: unknown
            app_id: 'no_e3da7633'
            desc: 1药网
          - name: mogujie
            key: unknown
            app_id: '1220042'
            desc: 蘑菇街
          - name: watsons
            key: unknown
            app_id: 'no_dcff3870'
            desc: 屈臣氏微商城
          - name: kaola
            key: unknown
            app_id: '1220061'
            desc: 考拉海购
          - name: xiaomishopping
            key: unknown
            app_id: '1220073'
            desc: 小米商城
          - name: '1688'
            key: unknown
            app_id: 'no_d32f95e1'
            desc: '1688'
          - name: 'huinong'
            key: unknown
            app_id: 'no_b81bfab7'
            desc: '惠农网'
          - name: yigou
            key: unknown
            app_id: '1220079'
            desc: 易购网
          - name: maoyan
            key: unknown
            app_id: 'no_26239ckc'
            desc: 猫眼电影
          - name: fliggy
            key: unknown
            app_id: 'no_dee75ac4'
            desc: 飞猪
    - class: APP
      name: EMAIL
      desc: 电子邮件
      app_list:
          - name: outlook
            key: outlook
            app_id: '1010032'
            desc: Outlook
          - name: gmail
            key: gmail
            app_id: '1010033'
            desc: Gmail
          - name: yahoo
            key: yahoo
            app_id: '1010034'
            desc: Yahoo邮箱
          - name: mail139
            key: mail139
            app_id: '1010012'
            desc: 139邮箱
          - name: 189mail
            key: 189mail
            app_id: '1010013'
            desc: 189邮箱
    - class: APP
      name: WEIBO
      desc: 社交自媒体
      app_list:
          - name: sinaweibo
            key: sinaweibo
            app_id: '1330001'
            desc: 新浪微博
          - name: twitter
            key: twitter
            app_id: '1330005'
            desc: Twitter
          - name: instagram
            key: instagram
            app_id: '1330014'
            desc: Instagram
          - name: huya
            key: huya
            app_id: '1550019'
            desc: 虎牙直播
          - name: momo
            key: momo
            app_id: '1030044'
            desc: 陌陌
          # - class: APP
          #   name: MAP
          #   desc: 地图应用
          #   app_list:
          #       - name: baidu-map
          #         packages:
          #             - com.baidu.BaiduMap
          #         app_id: '1440004'
          #         desc: 百度地图
          - name: amap
            key: unknown
            app_id: '1440003'
            desc: 高德地图
    - class: APP
      name: TRAVEL
      desc: 旅业预定
      app_list:
          - name: didi
            key: didi
            app_id: '1520001'
            desc: 滴滴出行
          - name: booking
            key: unknown
            app_id: 'no_fd75f788'
            desc: booking
          - name: ctrip
            key: unknown
            app_id: '1260004'
            desc: 携程旅行
          - name: qunar
            key: unknown
            app_id: '1260007'
            desc: 去哪儿
          - name: elong
            key: unknown
            app_id: '1260006'
            desc: 艺龙旅行
          - name: caocao
            key: caocao
            app_id: '1520058'
            desc: 曹操出行
          - name: tuniu
            key: unknown
            app_id: '1230009'
            desc: 途牛
          - name: huazhu
            key: unknown
            app_id: '1230003'
            desc: 华住会
          - name: shoulyu
            key: unknown
            app_id: 'no_0c89dad2'
            desc: 首旅如家
          - name: qiongyou
            key: unknown
            app_id: '1230035'
            desc: 穷游网
          - name: tongcheng
            key: unknown
            app_id: '1230010'
            desc: 同程旅行
          - name: caissa
            key: unknown
            app_id: 'no_b3a1da3a'
            desc: 凯撒旅行
          - name: jinjiang
            key: unknown
            app_id: '1230036'
            desc: 锦江酒店
          - name: chinaexpressair
            key: unknown
            app_id: 'no_7a9e53c5'
            desc: 华夏航空
          - name: luckyair
            key: unknown
            app_id: 'no_d5bd464c'
            desc: 祥鹏航空
    - class: APP
      name: NETDISK
      desc: 网络共享
      app_list:
          - name: onedrive
            key: onedrive
            app_id: 'no_b92dd0ca'
            desc: OneDrive
          - name: baidupan
            key: unknown
            app_id: '1280015'
            desc: 百度网盘
          - name: mi
            key: mi
            app_id: '1280032'
            desc: 小米云服务
          - name: wps
            key: wps
            app_id: '1280028'
            desc: WPS
    - class: APP
      name: EXPRESS
      desc: 快递包裹
      app_list:
          - name: shunfeng
            key: shunfeng
            app_id: '1240003'
            desc: 顺丰快递
          - name: yto
            key: yto
            app_id: '1240002'
            desc: 圆通快递
          - name: zto
            key: zto
            app_id: '1240007'
            desc: 中通快递
          - name: sto
            key: sto
            app_id: '1240005'
            desc: 申通快递
          - name: yunda
            key: yunda
            app_id: '1240004'
            desc: 韵达快递
          - name: ems
            key: ems
            app_id: '1240001'
            desc: 邮政EMS
          - name: dada
            key: dada
            app_id: '1520504'
            desc: 达达快递
          - name: deppon
            key: deppon
            app_id: '1240011'
            desc: 德邦快递
          - name: fcbox
            key: fcbox
            app_id: 'no_f3160ec4'
            desc: 丰巢
          - name: huolala
            key: huolala
            app_id: '1520501'
            desc: 货拉拉
    - class: APP
      name: OTHERS
      desc: 其他
      app_list:
          - name: '10086'
            key: '10086'
            app_id: 'no_55877b82'
            desc: 中国移动
          - name: '10010'
            key: '10010'
            app_id: '1220018'
            desc: 中国联通
          - name: '10000'
            key: '10000'
            app_id: 'no_592dc87c'
            desc: 中国电信
