fetch:
    - class: APP
      name: IM
      desc: 即时通讯
      app_list:
          - name: wechat
            packages:
                - com.tencent.mm
                - com.excelliance.dualaid
                - com.huihu.multplugin01
                - com.huihu.multplugin02
                - com.huihu.multplugin03
                - com.huihu.multplugin04
                - com.huihu.multplugin05
                - com.tencent.mm_cm
                - com.lbe.parallel
            app_id: '1030036'
            desc: 微信
          - name: wework
            packages:
                - com.tencent.wework
            app_id: '1030236'
            desc: 企业微信
          - name: qq
            packages:
                - com.tencent.qq
                - com.tencent.mobileqq
                - com.tencent.minihd.qq
                - com.tencent.mobileqq_cm
                - com.lbe.parallel
                - com.tencent.tim
            app_id: '1030001'
            desc: QQ
          - name: alipay
            packages:
                - com.eg.android.AlipayGphone
            app_id: '1290007'
            desc: 支付宝
          - name: douyin
            packages:
                - com.ss.android.ugc.aweme
            app_id: '1400036'
            desc: 抖音
          - name: kuaishou
            packages:
                - com.smile.gifmaker
            app_id: '1400026'
            desc: 快手
          - name: momo
            packages:
                - com.immomo.momo
            app_id: '1030044'
            desc: 陌陌
          - name: putong
            packages:
                - com.p1.mobile.putong
            app_id: '1030206'
            desc: 探探
          - name: whatsapp
            packages:
                - com.whatsapp
            app_id: '1030038'
            desc: WhatsApp
          - name: blued
            packages:
                - com.soft.blued
            app_id: '1030146'
            desc: Blued
          - name: keige
            packages:
                - com.tencent.karaoke
            app_id: '1390006'
            desc: 全民K歌
          - name: yy
            packages:
                - com.duowan.mobile
            app_id: '1030050'
            desc: YY语音
          - name: yujian
            packages:
                - net.iaround
            app_id: '1030056'
            desc: 遇见
          - name: feixin
            packages:
                - cn.com.fetion
            app_id: '1030028'
            desc: 飞信
          - name: skype
            packages:
                - com.skype.rover
                - com.skype.raider
            app_id: '1030027'
            desc: Skype
          - name: miliao
            packages:
                - com.xiaomi.channel
            app_id: '1030035'
            desc: 米聊
          - name: line
            packages:
                - jp.naver.line.android
            app_id: '1030043'
            desc: LINE
          - name: facebook
            packages:
                - com.facebook.katana
                - com.facebook.orca
            app_id: '1030045'
            desc: Facebook
          - name: renren
            packages:
                - com.renren.mobile.android
            app_id: '1030046'
            desc: 人人
          - name: yixin
            packages:
                - im.yixin
            app_id: '1030047'
            desc: 易信
          - name: laiwang
            packages:
                - com.alibaba.android.babylon
            app_id: '1030048'
            desc: 来往
          - name: wangxin
            packages:
                - com.alibaba.mobileim
            app_id: '1030049'
            desc: 旺信
          - name: talkbox
            packages:
                - com.gtomato.talkbox
            app_id: '1030051'
            desc: Talkbox
          - name: voxer
            packages:
                - com.rebelvox.voxer
            app_id: '1030052'
            desc: Voxer
          - name: viber
            packages:
                - com.viber.voip
            app_id: '1030053'
            desc: Viber
          - name: coco
            packages:
                - com.instanza.cocovoice
            app_id: '1030057'
            desc: Coco
          - name: kakao-talk
            packages:
                - com.kakao.talk
                - com.kakao.group
            app_id: '1030058'
            desc: KakaoTalk
          - name: raid-call
            packages:
                - raidcall.pack
                - com.raidcall
            app_id: '1030059'
            desc: RaidCall
          - name: youxin
            packages:
                - com.yx
            app_id: '1030060'
            desc: 有信
          - name: zello
            packages:
                - com.loudtalks
            app_id: '1030080'
            desc: Zello
          - name: hello-talk
            packages:
                - com.hellotalk
            app_id: '1030083'
            desc: HelloTalk
          - name: kee-chat
            packages:
                - com.keechat.client
            app_id: '1039982'
            desc: KeeChat
          - name: oovoo
            packages:
                - com.oovoo
            app_id: '1039981'
            desc: ooVoo
          - name: didi
            packages:
                - com.didirelease.view
            app_id: '1039966'
            desc: DiDi
          - name: nimbuzz
            packages:
                - com.nimbuzz
            app_id: '1039953'
            desc: Nimbuzz
          - name: imo
            packages:
                - com.imo.android.imoim
                - com.imo.android.imoimbeta
            app_id: '1030210'
            desc: IMO
          - name: telegram
            packages:
                - org.telegram.messenger
            app_id: '1030063'
            desc: Telegram
          - name: potato
            packages:
                - potato-chat
            app_id: '1030219'
            desc: 土豆聊天
          - name: wowchat
            packages:
                - com.zsdk.wowchat
            app_id: '1039998'
            desc: WowChat
          - name: sugram
            packages:
                - org.sugram
            app_id: '1030215'
            desc: Sugram
          - name: palmchat
            packages:
                - com.zenmen.palmchat
            app_id: '1030224'
            desc: 连信
          - name: batchat
            packages:
                - com.woyue.batchat
            app_id: '1039997'
            desc: 蝙蝠
          - name: discord
            packages:
                - com.discord
            app_id: '1039994'
            desc: Discord
          - name: safechat
            packages:
                - net.safechat.app
            app_id: '1039995'
            desc: SafeChat
    - class: APP
      name: SHOPPING
      desc: 电子商务
      app_list:
          - name: taobao
            packages:
                - com.taobao.taobao
            app_id: '1220007'
            desc: 淘宝
          - name: tmall
            packages:
                - com.tmall.wireless
            app_id: '1220002'
            desc: 天猫
          - name: jd
            packages:
                - com.jingdong.app.mall
            app_id: '1220005'
            desc: 京东
          - name: suning
            packages:
                - com.suning.mobile.ebuy
            app_id: '1220006'
            desc: 苏宁易购
          - name: dangdang
            packages:
                - com.dangdang.buy2
            app_id: '1220001'
            desc: 当当
          - name: dianping
            packages:
                - com.dianping.v1
            app_id: '1220050'
            desc: 大众点评
          - name: meituan
            packages:
                - com.sankuai.meituan
            app_id: '1220040'
            desc: 美团
          - name: eleme
            packages:
                - me.ele
            app_id: '1229997'
            desc: 饿了么
          - name: meituanwaimai
            packages:
                - com.sankuai.meituan.takeoutnew
            app_id: '1229996'
            desc: 美团外卖
          - name: zhuanzhuan
            packages:
                - com.wuba.zhuanzhuan
            app_id: '1430019'
            desc: 转转
          - name: pinduoduo
            packages:
                - com.xunmeng.pinduoduo
            app_id: '1220066'
            desc: 拼多多
          - name: idlefish
            packages:
                - com.taobao.idlefish
            app_id: '1220069'
            desc: 闲鱼
    - class: APP
      name: BROWSER
      desc: 浏览器
      app_list:
          - name: browser
            packages:
                - com.android.browser
                - com.sec.android.app.sbrowser
            app_id: '1569998'
            desc: 默认浏览器
          - name: chrome
            packages:
                - com.android.chrome
            app_id: '1560019'
            desc: Chrome
          - name: safari
            packages:
                - com.apple.mobilesafari
            app_id: '1560028'
            desc: Safari
          - name: opera
            packages:
                - com.oupeng.mini.android
            app_id: '1560007'
            desc: Opera
          - name: uc-web
            packages:
                - com.UCMobile
            app_id: '1560013'
            desc: UC浏览器
          - name: qq-browser
            packages:
                - com.tencent.mtt
            app_id: '1560011'
            desc: QQ浏览器
          - name: baidu-browser
            packages:
                - com.baidu.browser.apps
            app_id: '1560001'
            desc: 百度浏览器
          - name: dolphin
            packages:
                - com.dolphin.browser.xf
                - com.dolphin.browser.express.web
                - com.dolphin.browser.tuna
                - mobi.mgeek.TunnyBrowser
            app_id: '1560021'
            desc: 海豚浏览器
          - name: cheetah
            packages:
                - com.ijinshan.browser_fast
            app_id: '1560003'
            desc: 猎豹浏览器
          - name: sogou-browser
            packages:
                - sogou.mobile.explorer
            app_id: '1560002'
            desc: 搜狗浏览器
          - name: baidutieba
            packages:
                - com.baidu.tieba
            app_id: '1070006'
            desc: 百度贴吧
          - name: baidu-mobile
            packages:
                - com.baidu.searchbox
            app_id: '1560025'
            desc: 手机百度
          - name: qh-browser
            packages:
                - com.qihoo.appstore
            app_id: '1560004'
            desc: 360浏览器
    - class: APP
      name: EMAIL
      desc: 邮件
      app_list:
          - name: email
            packages:
                - com.android.email
                - com.google.android.email
                - com.lenovo.email
                - com.htc.android.mail
            app_id: '01003'
            desc: 自带邮件
          - name: qq-email
            packages:
                - com.tencent.androidqqmail
            app_id: '01007'
            desc: QQ邮箱
          - name: netease-master
            packages:
                - com.netease.mail
            app_id: '01996'
            desc: 网易邮箱大师
          - name: netease-email
            packages:
                - com.netease.mobimail
            app_id: '01997'
            desc: 网易邮箱
    - class: APP
      name: WEIBO
      desc: 媒体社交
      app_list:
          - name: weibo
            packages:
                - com.sina.weibo
            app_id: '1330001'
            desc: 新浪微博
          - name: tt
            packages:
                - com.tencent.WBlog
            app_id: '1330002'
            desc: 腾讯微博
          - name: twitter
            packages:
                - com.twitter.android
            app_id: '1330005'
            desc: Twitter
          - name: dingding
            packages:
                - com.alibaba.android.rimet
            app_id: '1030162'
            desc: 钉钉
          - name: toutiao
            packages:
                - com.ss.android.article.news
            app_id: '1380030'
            desc: 今日头条
          - name: bili
            packages:
                - tv.danmaku.bili
            app_id: '1400024'
            desc: 哔哩哔哩
          - name: youku
            packages:
                - com.youku.phone
            app_id: '1400004'
            desc: 优酷
          - name: iqiyi
            packages:
                - com.qiyi.video
            app_id: '1400010'
            desc: 爱奇艺
          - name: douyu
            packages:
                - air.tv.douyu.android
            app_id: '1550024'
            desc: 斗鱼直播
          - name: huya
            packages:
                - com.duowan.kiwi
            app_id: '1550019'
            desc: 虎牙直播
    - class: APP
      name: MAP
      desc: 地图
      app_list:
          - name: baidu-map
            packages:
                - com.baidu.BaiduMap
            app_id: '1440004'
            desc: 百度地图
          - name: google-map
            packages:
                - com.google.android.apps.maps
            app_id: '1440001'
            desc: Google地图
          - name: amap
            packages:
                - com.autonavi.minimap
            app_id: '1440003'
            desc: 高德地图
          - name: sougou-map
            packages:
                - com.sogou.map.android.maps
            app_id: '1440005'
            desc: 搜狗地图
          - name: soso-map
            packages:
                - com.tencent.map
            app_id: '1449998'
            desc: 腾讯地图
    - class: APP
      name: TRAVEL
      desc: 行程
      app_list:
          - name: umetrip
            packages:
                - com.umetrip.android.msky.app
            app_id: '1260010'
            desc: 航旅纵横
          - name: didicar
            packages:
                - com.sdu.didi.psnger
            app_id: '1520001'
            desc: 滴滴打车
          - name: kuaidi
            packages:
                - com.funcity.taxi.passenger
            app_id: '1520002'
            desc: 快的打车
          - name: ctrip
            packages:
                - ctrip.android.view
            app_id: '1260004'
            desc: 携程旅行
          - name: qunar
            packages:
                - com.Qunar
            app_id: '1260007'
            desc: 去哪儿
          - name: elong
            packages:
                - com.dp.android.elong
            app_id: '1260006'
            desc: 艺龙旅行
          - name: veryzhun
            packages:
                - vz.com
            app_id: '1260011'
            desc: 飞常准
          - name: rails12306
            packages:
                - com.MobileTicket
            app_id: '1260008'
            desc: 铁路12306
          - name: caocao
            packages:
                - cn.caocaokeji.user
            app_id: '1520058'
            desc: 曹操出行
          - name: hangban
            packages:
                - com.flightmanager.view
            app_id: '1269997'
            desc: 航班管家
          - name: dida
            packages:
                - com.didapinche.booking
            app_id: '1520008'
            desc: 嘀嗒出行
    - class: APP
      name: NETDISK
      desc: 网盘 & 笔记
      app_list:
          - name: baidupan
            packages:
                - com.baidu.netdisk
            app_id: '1280015'
            desc: 百度网盘
          - name: youdaonote
            packages:
                - com.yinxiang
            app_id: '1280025'
            desc: 印象笔记
          - name: youdaonote
            packages:
                - com.youdao.note
            app_id: '1289998'
            desc: 有道云笔记
    - class: APP
      name: KeyboardInput
      desc: 输入法
      app_list:
          - name: sogou-input
            packages:
                - com.sohu.inputmethod.sogou
            app_id: '1420005'
            desc: 搜狗输入法
          - name: baidu-input
            packages:
                - com.baidu.input
            app_id: '1420093'
            desc: 百度输入法
