max: 8
useFetch: true
useServerCloud: true
useBcp: true
useToolBox: true
useFakeButton: true
useAi: true
useLogin: true
useTraceLogin: true
useQuickFetch: true
hideCad: true
caseText: 案件
fetchText: 取证
devText: 设备
parseText: 解析
fetchButtonText: 取证
cloudButtonText: 云取证
cloudAppUrl: http://139.9.112.8:9699/test_app
cloudAppMd5: http://139.9.112.8:9699/test_md5
# useHardwareAcceleration: true
logo: logo.png
windowHeight: 1024
windowWidth: 1460
minHeight: 800
minWidth: 1280
center: true
tcpPort: 65222
httpPort: 9900
fetchPath: ./n_fetch
fetchExe: n_fetch.exe
parsePath: ./parse
parseExe: parse.exe
yqPath: ./yq
yqExe: yqRPC.exe
appQueryPath: ./AppQuery
appQueryExe: AppQuery.exe
quickFetchPath: ./QuickFetch
quickFetchExe: QuickFetchServer.exe
logFile: ./log/app.log
devPageUrl: http://localhost:8081/default.html
