max: 8
useFetch: true
useServerCloud: true
useBcp: true
useToolBox: true
useFakeButton: false
useAi: true
cloudAppUrl: http://139.9.112.8:9699/test_app
cloudAppMd5: http://139.9.112.8:9699/test_md5
# useHardwareAcceleration: true
logo: logo.png
windowHeight: 1024
windowWidth: 1460
minHeight: 768
minWidth: 1280
center: true
tcpPort: 65222
httpPort: 9900
fetchPath: ./n_fetch
fetchExe: n_fetch.exe
parsePath: ./parse
parseExe: parse.exe
yqPath: ./yq
yqExe: yqRPC.exe
logFile: ./log/app.log
devPageUrl: http://localhost:8081/default.html
