devPageUrl: http://localhost:8081/default.html
logo: logo.png
windowHeight: 1024
windowWidth: 1460
minHeight: 768
minWidth: 1280
center: true
max: 8
tcpPort: 65222
httpPort: 9900
fetchPath: ./n_fetch
fetchExe: n_fetch.exe
parsePath: ./parse
parseExe: parse.exe
publishPage: ./dist/default.html
logFile: ./log/app.log
useMode: 0
useServerCloud: true
