devPageUrl: http://localhost:8081/default.html
prodPageUrl: http://localhost:8081/default.html
title: 智能终端取证系统
author: 北京万盛华通科技有限公司
logo: logo.png
windowHeight: 1024
windowWidth: 1460
minHeight: 768
minWidth: 1280
center: true
max: 8
tcpPort: 65222
httpPort: 9900
fetchPath: ./n_fetch
fetchExe: n_fetch.exe
parsePath: ./parse
parseExe: parse.exe
rpcUri: tcp4://127.0.0.1:41622/
parsingUri: tcp4://127.0.0.1:60000/
platformUri: tcp4://127.0.0.1:50000/
publishPage: ./dist/default.html
logFile: ./log/app.log
useMode: 0
