devPageUrl: http://localhost:8081/default.html
prodPageUrl: http://localhost:8081/default.html
title: N次方手机多路取证塔-专业版
windowHeight: 1024
windowWidth: 1460
minHeight: 900
minWidth: 1280
isFullScreen: false
autoHideMenuBar: true
center: true
max: 2
rpcUri: tcp4://127.0.0.1:41622/
parsingUri: tcp4://127.0.0.1:60000/
devApi: http://127.0.0.1:3000/
prodApi: /
publishPage: ./dist/default.html
casePath: C:\TZSafe
isShowRenderer: false
logFile: ./log/app.log
userLogPath: ./data
readerPath: tools/ReportReader/ReportReader.exe
defenderPath: tools/PasswordTool/passtool.exe
bcpPath: tools/BcpTools/BcpGen.exe
update: update/update.exe
version: info.dat
