devPageUrl: http://localhost:8081/default.html
prodPageUrl: http://localhost:8081/default.html
title: N次方手机多路取证塔-专业版
author: 北京万盛华通科技有限公司
windowHeight: 1024
windowWidth: 1460
minHeight: 900
minWidth: 1280
center: true
max: 8
rpcUri: tcp4://127.0.0.1:41622/
parsingUri: tcp4://127.0.0.1:60000/
platformUri: tcp4://127.0.0.1:50000/
publishPage: ./dist/default.html
logFile: ./log/app.log
